import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight, Download, ExternalLink } from "lucide-react";

export const dynamic = "force-static";

export const metadata: Metadata = {
  title: "Zapost — Estudo de caso | Matheus Almeida Gomes",
  description: "Como o Zapost foi projetado: arquitetura SaaS multi-tenant, geração com IA, editor visual, filas, pagamentos e infraestrutura de produção.",
};

const pillars = [
  { number: "01", title: "Isolamento por tenant", text: "Dados de cada cliente separados por escopo de tenant no PostgreSQL, com acesso mediado pela aplicação e modelagem via Prisma." },
  { number: "02", title: "Geração resiliente", text: "Pipeline de conteúdo com RAG, embeddings vetoriais, busca em tempo real e fallback entre provedores de modelos." },
  { number: "03", title: "Processamento desacoplado", text: "Tarefas intensivas saem do fluxo da requisição e seguem para filas BullMQ com Redis, controle de concorrência e rate limiting distribuído." },
  { number: "04", title: "Edição no navegador", text: "Editor visual em Canvas com proporções dinâmicas, histórico de alterações e exportação em PNG, WebP, SVG em camadas e PDF." },
];

export default function ZapostCaseStudy() {
  return <>
    <header className="site-header case-header"><div className="shell header-inner"><Link className="brand" href="/" aria-label="Matheus Almeida Gomes, início"><span className="brand-mark">M<span>.</span></span><span>Matheus Almeida Gomes</span></Link><Link className="back-link" href="/#projetos"><ArrowLeft size={17} aria-hidden="true" /> Voltar aos projetos</Link></div></header>
    <main>
      <section className="case-hero"><div className="shell"><div className="case-breadcrumb"><Link href="/">Início</Link><span>/</span><Link href="/#projetos">Projetos</Link><span>/</span><strong>Zapost</strong></div><div className="case-hero-grid"><div><p className="eyebrow small">ESTUDO DE CASO / 01 · 2025 — ATUAL</p><h1>Zapost<span>.</span></h1><p className="case-lead">Um SaaS de criação de conteúdo visual com IA, pensado para manter a identidade de cada marca e dar controle ao usuário até a exportação.</p><div className="case-actions"><a className="button button-lime" href="https://lp.zapost.com.br/" target="_blank" rel="noopener noreferrer">Visitar produto <ArrowUpRight size={17} aria-hidden="true" /></a><a className="case-secondary" href="mailto:matheuszalax@gmail.com">Conversar sobre o projeto <ArrowUpRight size={17} aria-hidden="true" /></a></div></div><aside className="case-facts"><div><span>PAPEL</span><strong>Fundador · Engenheiro de Software Full-Stack</strong></div><div><span>ESCOPO</span><strong>Produto, arquitetura, desenvolvimento e operação</strong></div><div><span>BASE</span><strong>Next.js · TypeScript · PostgreSQL · Redis · Docker</strong></div></aside></div></div></section>
      <section className="case-intro section"><div className="shell case-text-grid"><p className="eyebrow small">O CONTEXTO</p><div><h2>Do tema ao carrossel pronto para publicar.</h2><p>O Zapost reúne pesquisa, geração de conteúdo, aplicação de identidade visual, edição e exportação num fluxo único. O desafio de engenharia foi conectar essas etapas sem perder a separação entre clientes, a resposta da interface ou a possibilidade de revisão humana.</p><p>Minha responsabilidade cobriu o ciclo completo: concepção do produto, desenho da arquitetura, implementação da aplicação e implantação em produção.</p></div></div></section>
      <section className="case-pillars section"><div className="shell"><div className="section-heading"><div><p className="eyebrow small">DECISÕES DE ENGENHARIA</p><h2>Como o sistema foi construído<span className="accent-dot">.</span></h2></div></div><div className="pillar-grid">{pillars.map(p => <article className="pillar" key={p.number}><span>{p.number}</span><h3>{p.title}</h3><p>{p.text}</p></article>)}</div></div></section>
      <section className="case-architecture section"><div className="shell"><div className="section-heading"><div><p className="eyebrow small">ARQUITETURA</p><h2>Da borda aos dados<span className="accent-dot">.</span></h2></div><p>Visão simplificada dos serviços descritos no currículo.</p></div><div className="system-map" role="img" aria-label="Cloudflare encaminha tráfego ao Nginx na VPS. O Nginx roteia a aplicação Next.js em Docker. A aplicação usa PostgreSQL, Redis e workers, além de serviços externos de IA e pagamentos."><div className="map-row"><div className="map-node"><small>ACESSO</small><strong>Usuário</strong><span>Navegador</span></div><div className="map-arrow" aria-hidden="true">→</div><div className="map-node"><small>BORDA</small><strong>Cloudflare</strong><span>Tunnel / proteção</span></div><div className="map-arrow" aria-hidden="true">→</div><div className="map-node"><small>VPS</small><strong>Nginx</strong><span>Proxy reverso / SSL</span></div><div className="map-arrow" aria-hidden="true">→</div><div className="map-node map-primary"><small>APLICAÇÃO</small><strong>Next.js</strong><span>UI, APIs e autenticação</span></div></div><div className="map-branch" aria-hidden="true">↓ &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↓ &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↓</div><div className="map-row map-lower"><div className="map-node"><small>DADOS</small><strong>PostgreSQL</strong><span>Prisma / tenants</span></div><div className="map-node"><small>TAREFAS</small><strong>Redis + BullMQ</strong><span>Workers e filas</span></div><div className="map-node"><small>INTEGRAÇÕES</small><strong>IA + pagamentos</strong><span>LLMs / webhooks</span></div></div></div><p className="map-note">Diagrama conceitual baseado nas tecnologias e responsabilidades descritas no currículo. Os detalhes internos foram simplificados para leitura.</p></div></section>
      <section className="case-detail section"><div className="shell case-text-grid"><p className="eyebrow small">RESOLUÇÃO DE PROBLEMAS</p><div><h2>Equilibrar flexibilidade, segurança e operação.</h2><div className="case-detail-list"><article><h3>Conteúdo com contexto</h3><p>O fluxo de geração combina dados de referência, busca atualizada e modelos de linguagem. O fallback entre provedores reduz a dependência de uma única integração e o resultado permanece editável.</p></article><article><h3>Eventos confiáveis</h3><p>Pagamentos via Stripe e Mercado Pago exigem validação de assinaturas e tratamento idempotente de webhooks para evitar duplicidade no processamento de eventos.</p></article><article><h3>Deploy contínuo</h3><p>A aplicação e os workers rodam em contêineres numa VPS Linux, com Nginx como proxy reverso e automação de entrega por GitHub Actions.</p></article><article><h3>Proteção da aplicação</h3><p>A solução contempla autenticação, políticas CSP e mitigação de SSRF e CSRF em pontos sensíveis do fluxo.</p></article></div></div></div></section>
      <section className="case-end"><div className="shell"><p className="eyebrow small">PRÓXIMO PASSO</p><h2>Quer entender melhor alguma decisão?</h2><div><a className="button button-lime" href="mailto:matheuszalax@gmail.com">Falar com Matheus <ArrowUpRight size={18} aria-hidden="true" /></a><a className="case-secondary" href="/curriculo-matheus-almeida-gomes.pdf" download>Baixar currículo <Download size={18} aria-hidden="true" /></a></div></div></section>
    </main><footer className="footer"><div className="shell footer-inner"><span>© {new Date().getFullYear()} Matheus Almeida Gomes</span><Link href="/">Voltar ao início <ExternalLink size={14} aria-hidden="true" /></Link></div></footer>
  </>;
}
