import Link from "next/link";
import { ArrowDownRight, ArrowRight, ArrowUpRight, Download, Mail } from "lucide-react";

const groups = [
  { title: "Frontend", items: ["TypeScript", "React", "Next.js", "Tailwind CSS", "Canvas"] },
  { title: "Backend & dados", items: ["Node.js", "APIs REST", "PostgreSQL", "Prisma", "Redis"] },
  { title: "IA aplicada", items: ["LLMs", "RAG", "Embeddings", "Busca vetorial", "OpenRouter"] },
  { title: "Infraestrutura", items: ["Docker", "Nginx", "Cloudflare", "GitHub Actions", "Linux VPS"] },
];

export default function Home() {
  return <>
    <header className="site-header" id="top"><div className="shell header-inner">
      <Link className="brand" href="/" aria-label="Matheus Almeida Gomes, início"><span className="brand-mark">M<span>.</span></span><span>Matheus Almeida Gomes</span></Link>
      <nav aria-label="Navegação principal" className="main-nav"><a href="#projetos">Projetos</a><a href="#sobre">Sobre</a><a href="#stack">Stack</a><a href="#contato">Contato</a></nav>
      <a className="header-contact" href="mailto:matheuszalax@gmail.com">Vamos conversar <ArrowUpRight size={15} aria-hidden="true" /></a>
    </div></header>
    <main>
      <section className="hero shell" aria-labelledby="hero-title"><div className="hero-main">
        <p className="eyebrow"><span className="eyebrow-line" /> ENGENHEIRO DE SOFTWARE · FULL-STACK</p>
        <h1 id="hero-title">Produtos digitais,<br /><em>da arquitetura</em><br />à produção.</h1>
        <p className="hero-copy">Desenvolvo aplicações web com foco em produto, engenharia sólida e operação real. Da regra de negócio ao deploy.</p>
        <div className="hero-actions"><a className="button button-dark" href="#projetos">Explorar projetos <ArrowDownRight size={18} aria-hidden="true" /></a><a className="button button-outline" href="/curriculo-matheus-almeida-gomes.pdf" download>Baixar currículo <Download size={17} aria-hidden="true" /></a></div>
        <div className="hero-social" aria-label="Perfis profissionais"><a href="https://github.com/matheuszalax" target="_blank" rel="noopener noreferrer">GitHub <ArrowUpRight size={14} aria-hidden="true" /></a><a href="https://www.linkedin.com/in/matheus-almeida-gomes-dev/" target="_blank" rel="noopener noreferrer">LinkedIn <ArrowUpRight size={14} aria-hidden="true" /></a><a href="mailto:matheuszalax@gmail.com">E-mail <ArrowUpRight size={14} aria-hidden="true" /></a></div>
      </div><aside className="hero-aside" aria-label="Áreas de atuação"><div className="aside-top"><span>01 / PERFIL</span><span className="aside-cross" aria-hidden="true">✳</span></div><div className="aside-content"><p>Construindo produtos completos, com atenção ao que acontece depois do lançamento.</p><div className="aside-list"><span>SaaS multi-tenant</span><span>IA aplicada</span><span>Infraestrutura & deploy</span></div></div><div className="aside-bottom"><span>CONSOLAÇÃO · MG, BRASIL</span><span>REMOTO E HÍBRIDO</span></div></aside></section>
      <section id="projetos" className="section project-section" aria-labelledby="projects-title"><div className="shell"><div className="section-heading"><div><p className="eyebrow small">01 / PROJETO EM DESTAQUE</p><h2 id="projects-title">Engenharia em prática<span className="accent-dot">.</span></h2></div><p>Um produto em produção, do conceito à infraestrutura.</p></div>
        <article className="project-card"><div className="project-copy"><div className="project-meta"><span>PRODUTO SAAS · 2025 — ATUAL</span><span className="live-label"><span /> EM PRODUÇÃO</span></div><div><p className="project-number">PROJETO / 01</p><h3>Zapost</h3><p className="project-intro">Criação e edição de conteúdo visual com IA, identidade de marca e controle total no navegador.</p></div><p className="project-description">Concebi e desenvolvi a plataforma de ponta a ponta: arquitetura multi-tenant, geração com contexto, filas para tarefas pesadas, editor visual e pagamentos integrados.</p><div className="tags"><span>Next.js</span><span>TypeScript</span><span>PostgreSQL</span><span>Redis</span><span>Docker</span></div><div className="project-links"><Link href="/projetos/zapost">Ver estudo de caso <ArrowUpRight size={18} aria-hidden="true" /></Link><a href="https://lp.zapost.com.br/" target="_blank" rel="noopener noreferrer">Visitar produto <ArrowUpRight size={18} aria-hidden="true" /></a><a href="https://github.com/matheuszalax/zapost-portfolio-pt" target="_blank" rel="noopener noreferrer">Código e arquitetura <ArrowUpRight size={18} aria-hidden="true" /></a></div></div>
        <div className="project-visual" role="img" aria-label="Diagrama resumido: Next.js conecta APIs e filas de processamento; dados em PostgreSQL e integrações com IA e pagamentos"><div className="visual-caption"><span>ARQUITETURA / VISÃO GERAL</span><span>001</span></div><div className="architecture"><div className="architecture-row architecture-top"><div className="arch-box accent"><span>01 / INTERFACE</span><strong>Next.js + editor Canvas</strong><small>Experiência, edição e exportação</small></div></div><div className="arch-line" aria-hidden="true" /><div className="architecture-row split"><div className="arch-box"><span>02 / APLICAÇÃO</span><strong>APIs + autenticação</strong><small>Regras e isolamento por tenant</small></div><div className="arch-box"><span>03 / PROCESSAMENTO</span><strong>BullMQ + Redis</strong><small>Geração e tarefas assíncronas</small></div></div><div className="arch-line" aria-hidden="true" /><div className="architecture-row split"><div className="arch-box"><span>04 / DADOS</span><strong>PostgreSQL + Prisma</strong><small>Persistência relacional</small></div><div className="arch-box"><span>05 / EXTERNO</span><strong>LLMs + pagamentos</strong><small>Provedores e webhooks</small></div></div></div><div className="visual-footer"><span>DO NAVEGADOR À PRODUÇÃO</span><ArrowUpRight size={16} aria-hidden="true" /></div></div></article>
      </div></section>
      <section id="sobre" className="section about-section" aria-labelledby="about-title"><div className="shell about-grid"><div><p className="eyebrow small">02 / SOBRE</p><h2 id="about-title">Pensar o produto.<br />Construir o sistema.<br /><span>Operar com confiança.</span></h2></div><div className="about-body"><p>Sou Matheus, engenheiro de software full-stack e fundador do Zapost. Minha atuação conecta decisões de produto, desenvolvimento de interfaces, modelagem de dados e infraestrutura de produção.</p><p>Tenho experiência com SaaS multi-tenant, integração de IA com RAG, processamento assíncrono e implantação contínua em VPS. Curso Bacharelado em Engenharia de Software na UNINTER.</p><a href="mailto:matheuszalax@gmail.com">Entrar em contato <ArrowUpRight size={18} aria-hidden="true" /></a></div></div></section>
      <section id="stack" className="section stack-section" aria-labelledby="stack-title"><div className="shell"><div className="section-heading"><div><p className="eyebrow small">03 / FERRAMENTAS</p><h2 id="stack-title">Stack de trabalho<span className="accent-dot">.</span></h2></div><p>Tecnologias usadas para construir, integrar e manter produtos.</p></div><div className="stack-grid">{groups.map((group, i) => <div className="stack-group" key={group.title}><span className="stack-index">0{i + 1}</span><h3>{group.title}</h3><ul>{group.items.map(item => <li key={item}>{item}</li>)}</ul></div>)}</div></div></section>
      <section id="contato" className="contact-section" aria-labelledby="contact-title"><div className="shell contact-inner"><div><p className="eyebrow small">04 / CONTATO</p><h2 id="contact-title">Vamos construir<br />algo relevante<span>.</span></h2><p>Aberto a oportunidades em engenharia de software, produtos digitais e colaboração técnica.</p></div><div className="contact-links"><a className="contact-primary" href="mailto:matheuszalax@gmail.com"><Mail size={21} aria-hidden="true" /> matheuszalax@gmail.com <ArrowUpRight size={21} aria-hidden="true" /></a><a href="https://www.linkedin.com/in/matheus-almeida-gomes-dev/" target="_blank" rel="noopener noreferrer">LinkedIn <ArrowUpRight size={18} aria-hidden="true" /></a><a href="https://github.com/matheuszalax" target="_blank" rel="noopener noreferrer">GitHub <ArrowUpRight size={18} aria-hidden="true" /></a><a href="/curriculo-matheus-almeida-gomes.pdf" download>Baixar currículo <Download size={18} aria-hidden="true" /></a></div></div></section>
    </main>
    <footer className="footer"><div className="shell footer-inner"><span>© {new Date().getFullYear()} Matheus Almeida Gomes</span><span>Engenharia de software · Brasil</span><a href="#top">Voltar ao topo <ArrowRight size={15} aria-hidden="true" /></a></div></footer>
  </>;
}
